export const PROVINCE_CITY: Record<string, string> = {
  'Kinshasa':       'Kinshasa,CD',
  'Kongo Central':  'Matadi,CD',
  'Kasaï-Central':  'Kananga,CD',
  'Kasaï':          'Luebo,CD',
  'Kasaï-Oriental': 'Mbuji-Mayi,CD',
  'Sud-Kivu':       'Bukavu,CD',
  'Nord-Kivu':      'Goma,CD',
  'Maniema':        'Kindu,CD',
  'Tanganyika':     'Kalemie,CD',
  'Haut-Katanga':   'Lubumbashi,CD',
  'Lualaba':        'Kolwezi,CD',
  'Sankuru':        'Lodja,CD',
  'Ituri':          'Bunia,CD',
  'Haut-Uele':      'Isiro,CD',
  'Tshopo':         'Kisangani,CD',
  'Équateur':       'Mbandaka,CD',
  'Tshuapa':        'Boende,CD',
  'Lomami':         'Kabinda,CD',
  'Mai-Ndombe':     'Inongo,CD',
  'Kwango':         'Kenge,CD',
  'Kwilu':          'Kikwit,CD',
  'Nord-Ubangi':    'Gbadolite,CD',
  'Mongala':        'Lisala,CD',
  'Sud-Ubangi':     'Gemena,CD',
  'Bas-Uele':       'Buta,CD',
  'Haut-Lomami':    'Kamina,CD',
}

export const ALL_PROVINCES = Object.keys(PROVINCE_CITY)
